base_model: runwayml/stable-diffusion-v1-5
resolution: 512
train_batch_size: 1
gradient_accumulation_steps: 8
max_train_steps: 2000
learning_rate: 1e-4
dataset:
  images_dir: data/processed/images
  captions_dir: data/processed/captions
lora:
  r: 8
  alpha: 16
  dropout: 0.05
output_dir: weights/sd15/lora
seed: 42
